(add-hook 'elixir-mode-hook #'lsp-deferred)
(add-hook 'ruby-mode-hook #'lsp-deferred)
(setq lsp-clients-elixir-server-executable "~/elixir-ls/release/language_server.sh")
(setq lsp-enable-file-watchers nil)
(setq rustic-lsp-server 'rust-analyzer)
